export const countries = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua And Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia",
  "Bosnia And Herzegovina",
  "Botswana",
  "Bouvet Island",
  "Brazil",
  "British Indian Ocean Territory",
  "Brunei Darussalam",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cape Verde",
  "Cayman Islands",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Christmas Island",
  "Cocos (keeling) Islands",
  "Colombia",
  "Comoros",
  "Congo",
  "Congo, The Democratic Republic Of The",
  "Cook Islands",
  "Costa Rica",
  "Cote D'ivoire",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "East Timor",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Ethiopia",
  "Falkland Islands (malvinas)",
  "Faroe Islands",
  "Fiji",
  "Finland",
  "France",
  "French Guiana",
  "French Polynesia",
  "French Southern Territories",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guinea",
  "Guinea-bissau",
  "Guyana",
  "Haiti",
  "Heard Island And Mcdonald Islands",
  "Holy See (vatican City State)",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran, Islamic Republic Of",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakstan",
  "Kenya",
  "Kiribati",
  "Korea, Democratic People's Republic Of",
  "Korea, Republic Of",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Lao People's Democratic Republic",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libyan Arab Jamahiriya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macau",
  "Macedonia, The Former Yugoslav Republic Of",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Martinique",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Mexico",
  "Micronesia, Federated States Of",
  "Moldova, Republic Of",
  "Monaco",
  "Mongolia",
  "Montserrat",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "Netherlands Antilles",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Niue",
  "Norfolk Island",
  "Northern Mariana Islands",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestinian Territory, Occupied",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Pitcairn",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Reunion",
  "Romania",
  "Russian Federation",
  "Rwanda",
  "Saint Helena",
  "Saint Kitts And Nevis",
  "Saint Lucia",
  "Saint Pierre And Miquelon",
  "Saint Vincent And The Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome And Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Georgia And The South Sandwich Islands",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Svalbard And Jan Mayen",
  "Swaziland",
  "Sweden",
  "Switzerland",
  "Syrian Arab Republic",
  "Taiwan, Province Of China",
  "Tajikistan",
  "Tanzania, United Republic Of",
  "Thailand",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad And Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks And Caicos Islands",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "United States Minor Outlying Islands",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela",
  "Viet Nam",
  "Virgin Islands, British",
  "Virgin Islands, U.s.",
  "Wallis And Futuna",
  "Western Sahara",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

export const languages = [
  "Mandarin Chinese",
  "Spanish",
  "English",
  "Hindi",
  "Arabic",
  "Bengali",
  "Portuguese",
  "Russian",
  "Japanese",
  "Punjabi",
  "German",
  "Javanese",
  "Wu Chinese",
  "Korean",
  "French",
  "Telugu",
  "Vietnamese",
  "Marathi",
  "Tamil",
  "Urdu",
  "Turkish",
  "Italian",
  "Yue Chinese",
  "Thai",
  "Gujarati",
  "Jin Chinese",
  "Southern Min",
  "Persian (Farsi)",
  "Polish",
  "Pashto",
  "Kannada",
  "Xiang Chinese",
  "Malayalam",
  "Sundanese",
  "Hausa",
  "Odia (Oriya)",
  "Burmese",
  "Hakka Chinese",
  "Ukrainian",
  "Bhojpuri",
  "Tagalog",
  "Yoruba",
  "Maithili",
  "Uzbek",
  "Sindhi",
  "Amharic",
  "Fula",
  "Romanian",
  "Oromo",
  "Igbo",
  "Azerbaijani",
  "Awadhi",
  "Gan Chinese",
  "Cebuano",
  "Dutch",
  "Kurdish",
  "Serbo-Croatian",
  "Malagasy",
  "Saraiki",
  "Nepali",
  "Sinhalese",
  "Chittagonian",
  "Zhuang",
  "Khmer",
  "Turkmen",
  "Assamese",
  "Madurese",
  "Somali",
  "Magahi",
  "Haryanvi",
  "Hungarian",
  "Chhattisgarhi",
  "Greek",
  "Chewa",
  "Deccan",
  "Akan",
  "Kazakh",
  "Northern Min",
  "Sylheti",
  "Zulu",
  "Czech",
  "Kinyarwanda",
  "Dhundhari",
  "Haitian Creole",
  "Eastern Min",
  "Ilocano",
  "Quechua",
  "Kirundi",
  "Swedish",
  "Hmong",
  "Shona",
  "Uyghur",
  "Hiligaynon",
  "Mossi",
  "Xhosa",
  "Belarusian",
  "Balochi",
  "Konkani",
  "Zazaki",
  "Tigrinya",
];

export const professions = [
  "Acupuncturist",
  "Actor",
  "Air Traffic Controller",
  "Animal Trainer",
  "Animator",
  "App Developer",
  "Architect",
  "Athlete",
  "Athletic Coach",
  "Athletic Trainer",
  "Audio Engineer",
  "Author",
  "Baker",
  "Bank Teller",
  "Barber",
  "Biologist",
  "Biomedical Engineer",
  "Brick Mason",
  "Business Analyst",
  "Carpenter",
  "Cartographer",
  "Chef",
  "Chiropractor",
  "Cinematographer",
  "Civil Engineer",
  "Claims Adjuster",
  "Clinical Psychologist",
  "Coach",
  "Commercial Diver",
  "Computer Hardware Engineer",
  "Construction Manager",
  "Construction Worker",
  "Consultant",
  "Cop",
  "Copywriter",
  "Cosmetologist",
  "Court Reporter",
  "Customer Service Manager",
  "Customer Service Representative",
  "Data Analyst",
  "Database Administrator",
  "Dancer",
  "Dental Hygienist",
  "Dentist",
  "Desktop Publisher",
  "Detective",
  "Dietitian",
  "Digital Marketing Manager",
  "Director of Photography",
  "Dispatcher",
  "Doctor",
  "E-commerce Specialist",
  "Economist",
  "Electrician",
  "Elevator Installer and Repairer",
  "Energy Analyst",
  "Engineer",
  "Entrepreneur",
  "Environmental Engineer",
  "Event Planner",
  "Executive Assistant",
  "Farmer",
  "Fashion Designer",
  "Fashion Stylist",
  "Financial Advisor",
  "Financial Analyst",
  "Financial Planner",
  "Fire Inspector",
  "Firefighter",
  "Fitness Trainer",
  "Flight Attendant",
  "Florist",
  "Food Scientist",
  "Forensic Scientist",
  "Funeral Director",
  "Game Designer",
  "Geologist",
  "Glassblower",
  "Grant Writer",
  "Graphic Designer",
  "Gynecologist",
  "Hair Stylist",
  "Hairdresser",
  "Hazardous Materials Removal Worker",
  "Health Educator",
  "Historian",
  "Home Health Aide",
  "Hotel Housekeeper",
  "Hotel Manager",
  "Human Resources Generalist",
  "Human Resources Manager",
  "Information Security Analyst",
  "Interpreter",
  "Interpreter/Translator",
  "Investment Banker",
  "Investigator",
  "Investor Relations Specialist",
  "IT Manager",
  "Janitor",
  "Journalist",
  "Judge",
  "Landscaper",
  "Landscape Architect",
  "Lawyer",
  "Librarian",
  "Linguist",
  "Loan Officer",
  "Locksmith",
  "Logistician",
  "Magazine Editor",
  "Management Analyst",
  "Marketing Manager",
  "Makeup Artist",
  "Mechanic",
  "Mechanical Engineer",
  "Medical Assistant",
  "Medical Technologist",
  "Meteorologist",
  "Midwife",
  "Military Officer",
  "Miner",
  "Museum Curator",
  "Musician",
  "Network Administrator",
  "Nurse",
  "Occupational Therapist",
  "Oil Rig Worker",
  "Operations Manager",
  "Optometrist",
  "Paralegal",
  "Paramedic",
  "Pharmacist",
  "Phlebotomist",
  "Physical Therapist",
  "Physician Assistant",
  "Pilot",
  "Plumber",
  "Police Officer",
  "Professor",
  "Project Manager",
  "Public Relations Specialist",
  "Radiologic Technologist",
  "Real Estate Agent",
  "Real Estate Broker",
  "Receptionist",
  "Recreation Worker",
  "Research Assistant",
  "Retail Sales Associate",
  "Sales Manager",
  "Salesperson",
  "School Counselor",
  "Scientist",
  "Security Guard",
  "Software Developer",
  "Social Worker",
  "Statistician",
  "Stock Clerk",
  "Substance Abuse Counselor",
  "Surgeon",
  "Surveyor",
  "Taxi Driver",
  "Teacher",
  "Technical Writer",
  "Telecommunications Technician",
  "Tour Guide",
  "Travel Agent",
  "Veterinarian",
  "Video Editor",
  "Welder",
  "Web Developer",
  "Writer",
];
